import { NextRequest, NextResponse } from 'next/server'
import CrewRAGIntegrationSystem from '@/lib/crew-rag-integration'

// Crew Response API with RAG Integration
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { crewMember, query, autoSelect } = body

    const crewRAGSystem = new CrewRAGIntegrationSystem()

    let selectedCrewMember = crewMember

    // Auto-select crew member based on query relevance if requested
    if (autoSelect && !crewMember) {
      selectedCrewMember = await crewRAGSystem.analyzeQueryRelevance(query)
    }

    if (!selectedCrewMember) {
      return NextResponse.json(
        { success: false, error: 'crewMember is required' },
        { status: 400 }
      )
    }

    if (!query) {
      return NextResponse.json(
        { success: false, error: 'query is required' },
        { status: 400 }
      )
    }

    // Check if crew member exists
    if (!crewRAGSystem.hasCrewMember(selectedCrewMember)) {
      return NextResponse.json(
        { success: false, error: `Crew member ${selectedCrewMember} not found` },
        { status: 404 }
      )
    }

    // Generate response with RAG integration
    const response = await crewRAGSystem.generateResponse(selectedCrewMember, query)

    return NextResponse.json({
      success: true,
      data: response,
      message: `Response generated by ${response.crewMember} using ${response.localContext ? 'local context' : 'RAG system'}`
    })

  } catch (error: any) {
    console.error('Crew response error:', error)
    return NextResponse.json(
      { 
        success: false, 
        error: 'Failed to generate crew response',
        details: error.message 
      }, 
      { status: 500 }
    )
  }
}

export async function GET(request: NextRequest) {
  try {
    const crewRAGSystem = new CrewRAGIntegrationSystem()
    const url = new URL(request.url)
    const action = url.searchParams.get('action')

    switch (action) {
      case 'crew-list':
        const crewMembers = crewRAGSystem.getAllCrewMembers()
        return NextResponse.json({
          success: true,
          data: crewMembers,
          message: 'All crew members retrieved'
        })

      case 'analyze-relevance':
        const query = url.searchParams.get('query')
        if (!query) {
          return NextResponse.json(
            { success: false, error: 'query parameter required' },
            { status: 400 }
          )
        }

        const relevantCrew = await crewRAGSystem.analyzeQueryRelevance(query)
        return NextResponse.json({
          success: true,
          data: { crewMember: relevantCrew, query },
          message: `Most relevant crew member for query: ${query}`
        })

      case 'crew-context':
        const crewMember = url.searchParams.get('crewMember')
        if (!crewMember) {
          return NextResponse.json(
            { success: false, error: 'crewMember parameter required' },
            { status: 400 }
          )
        }

        if (!crewRAGSystem.hasCrewMember(crewMember)) {
          return NextResponse.json(
            { success: false, error: `Crew member ${crewMember} not found` },
            { status: 404 }
          )
        }

        const context = await crewRAGSystem.getCrewContext(crewMember)
        return NextResponse.json({
          success: true,
          data: context,
          message: `Crew context retrieved for ${crewMember}`
        })

      default:
        return NextResponse.json({
          success: true,
          data: {
            availableActions: [
              'crew-list',
              'analyze-relevance',
              'crew-context'
            ],
            usage: {
              post: {
                description: 'Generate crew response with RAG integration',
                body: {
                  crewMember: 'string (optional if autoSelect=true)',
                  query: 'string (required)',
                  autoSelect: 'boolean (optional)'
                }
              },
              get: {
                'crew-list': 'GET /api/crew-response?action=crew-list',
                'analyze-relevance': 'GET /api/crew-response?action=analyze-relevance&query=your_query',
                'crew-context': 'GET /api/crew-response?action=crew-context&crewMember=crew_id'
              }
            }
          },
          message: 'Crew Response API with RAG Integration'
        })
    }

  } catch (error: any) {
    console.error('Crew response GET error:', error)
    return NextResponse.json(
      { 
        success: false, 
        error: 'Internal server error',
        details: error.message 
      }, 
      { status: 500 }
    )
  }
}
