var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/mcp/status/route.js")
R.c("server/chunks/9f1d4_next_ad1dcc7e._.js")
R.c("server/chunks/9f1d4_@opentelemetry_api_build_esm_12bd161d._.js")
R.c("server/chunks/node_modules_@supabase_storage-js_dist_module_ccb8d6df._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_02e1b12e._.js")
R.c("server/chunks/node_modules_d4538731._.js")
R.c("server/chunks/[root-of-the-server]__4b681c7d._.js")
R.c("server/chunks/dashboard__next-internal_server_app_api_mcp_status_route_actions_fcfd3586.js")
R.m("[project]/dashboard/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/dashboard/app/api/mcp/status/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/dashboard/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/dashboard/app/api/mcp/status/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
