// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/auth/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/signin">> = Specific
  const handler = {} as typeof import("../../../app/auth/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/clear-state/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clear-state">> = Specific
  const handler = {} as typeof import("../../../app/clear-state/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/creative/[projectId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creative/[projectId]">> = Specific
  const handler = {} as typeof import("../../../app/creative/[projectId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/analytics">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/projects/[projectId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/projects/[projectId]">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/projects/[projectId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/vector-priority/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/vector-priority">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/vector-priority/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/demos/theme-gallery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demos/theme-gallery">> = Specific
  const handler = {} as typeof import("../../../app/demos/theme-gallery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/errors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/errors">> = Specific
  const handler = {} as typeof import("../../../app/errors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/gallery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gallery">> = Specific
  const handler = {} as typeof import("../../../app/gallery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/mcp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mcp">> = Specific
  const handler = {} as typeof import("../../../app/mcp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/mcp/status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mcp/status">> = Specific
  const handler = {} as typeof import("../../../app/mcp/status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/observation-lounge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/observation-lounge">> = Specific
  const handler = {} as typeof import("../../../app/observation-lounge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/[projectId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]">> = Specific
  const handler = {} as typeof import("../../../app/projects/[projectId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/new">> = Specific
  const handler = {} as typeof import("../../../app/projects/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../../app/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/preview">> = Specific
  const handler = {} as typeof import("../../../app/projects/preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/quiz/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quiz">> = Specific
  const handler = {} as typeof import("../../../app/quiz/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/reports/architecture/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/architecture">> = Specific
  const handler = {} as typeof import("../../../app/reports/architecture/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/reports/observation-lounge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/observation-lounge">> = Specific
  const handler = {} as typeof import("../../../app/reports/observation-lounge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test">> = Specific
  const handler = {} as typeof import("../../../app/test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/themes/a11y/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/themes/a11y">> = Specific
  const handler = {} as typeof import("../../../app/themes/a11y/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/themes/template/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/themes/template">> = Specific
  const handler = {} as typeof import("../../../app/themes/template/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/wizard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wizard">> = Specific
  const handler = {} as typeof import("../../../app/wizard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/workflows/management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workflows/management">> = Specific
  const handler = {} as typeof import("../../../app/workflows/management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/workflows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workflows">> = Specific
  const handler = {} as typeof import("../../../app/workflows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/agent/engage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/engage">> = Specific
  const handler = {} as typeof import("../../../app/api/agent/engage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/agent/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/status">> = Specific
  const handler = {} as typeof import("../../../app/api/agent/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/custom-signin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/custom-signin">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/custom-signin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/codebase-changes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/codebase-changes">> = Specific
  const handler = {} as typeof import("../../../app/api/codebase-changes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/content/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content/delete">> = Specific
  const handler = {} as typeof import("../../../app/api/content/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/content/retrieve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content/retrieve">> = Specific
  const handler = {} as typeof import("../../../app/api/content/retrieve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/content/store/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content/store">> = Specific
  const handler = {} as typeof import("../../../app/api/content/store/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/crew/observations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crew/observations">> = Specific
  const handler = {} as typeof import("../../../app/api/crew/observations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/crew/thoughts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crew/thoughts">> = Specific
  const handler = {} as typeof import("../../../app/api/crew/thoughts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/data/crew-contributions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/crew-contributions">> = Specific
  const handler = {} as typeof import("../../../app/api/data/crew-contributions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/data/learning-categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/learning-categories">> = Specific
  const handler = {} as typeof import("../../../app/api/data/learning-categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/data/learning-metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/learning-metrics">> = Specific
  const handler = {} as typeof import("../../../app/api/data/learning-metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/data/progress/[taskId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/progress/[taskId]">> = Specific
  const handler = {} as typeof import("../../../app/api/data/progress/[taskId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/data/recent-memories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/recent-memories">> = Specific
  const handler = {} as typeof import("../../../app/api/data/recent-memories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/data/vectors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/vectors">> = Specific
  const handler = {} as typeof import("../../../app/api/data/vectors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events">> = Specific
  const handler = {} as typeof import("../../../app/api/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ingest/youtube/batch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ingest/youtube/batch">> = Specific
  const handler = {} as typeof import("../../../app/api/ingest/youtube/batch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ingest/youtube/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ingest/youtube">> = Specific
  const handler = {} as typeof import("../../../app/api/ingest/youtube/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/knowledge/query/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/knowledge/query">> = Specific
  const handler = {} as typeof import("../../../app/api/knowledge/query/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/lounge/avatars/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lounge/avatars">> = Specific
  const handler = {} as typeof import("../../../app/api/lounge/avatars/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/lounge/crew-advice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lounge/crew-advice">> = Specific
  const handler = {} as typeof import("../../../app/api/lounge/crew-advice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/lounge/crew-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lounge/crew-status">> = Specific
  const handler = {} as typeof import("../../../app/api/lounge/crew-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/lounge/latest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lounge/latest">> = Specific
  const handler = {} as typeof import("../../../app/api/lounge/latest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/[...endpoint]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/[...endpoint]">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/[...endpoint]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/crew/roster/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/crew/roster">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/crew/roster/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/errors/[id]/ignore/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/errors/[id]/ignore">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/errors/[id]/ignore/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/errors/[id]/resolve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/errors/[id]/resolve">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/errors/[id]/resolve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/errors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/errors">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/errors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/settings">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/settings/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/settings/test">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/settings/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/status/admin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/status/admin">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/status/admin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/status">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/workflows/execute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/workflows/execute">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/workflows/execute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/workflows/executions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/workflows/executions">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/workflows/executions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/workflows/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/workflows/save">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/workflows/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/workflows/storage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/workflows/storage">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/workflows/storage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/progress/[taskId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/progress/[taskId]">> = Specific
  const handler = {} as typeof import("../../../app/api/progress/[taskId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/revalidate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/revalidate">> = Specific
  const handler = {} as typeof import("../../../app/api/revalidate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/create-table/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/create-table">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/create-table/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/diagnose/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/diagnose">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/diagnose/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/retrieve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/retrieve">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/retrieve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/store/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/store">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/store/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/test-supabase/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/test-supabase">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/test-supabase/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/socket/io/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/socket/io">> = Specific
  const handler = {} as typeof import("../../../app/api/socket/io/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/socket/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/socket">> = Specific
  const handler = {} as typeof import("../../../app/api/socket/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sync/pending/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync/pending">> = Specific
  const handler = {} as typeof import("../../../app/api/sync/pending/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sync/update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync/update">> = Specific
  const handler = {} as typeof import("../../../app/api/sync/update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/theme/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/theme/test">> = Specific
  const handler = {} as typeof import("../../../app/api/theme/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/themes/[theme]/tokens/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/themes/[theme]/tokens">> = Specific
  const handler = {} as typeof import("../../../app/api/themes/[theme]/tokens/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/themes/dashboard/tokens/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/themes/dashboard/tokens">> = Specific
  const handler = {} as typeof import("../../../app/api/themes/dashboard/tokens/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/themes/project/[project]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/themes/project/[project]">> = Specific
  const handler = {} as typeof import("../../../app/api/themes/project/[project]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/themes/project/[project]/tokens/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/themes/project/[project]/tokens">> = Specific
  const handler = {} as typeof import("../../../app/api/themes/project/[project]/tokens/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/workflows/[id]/mermaid/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workflows/[id]/mermaid">> = Specific
  const handler = {} as typeof import("../../../app/api/workflows/[id]/mermaid/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
