// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/auth/signin" | "/clear-state" | "/creative/[projectId]" | "/dashboard" | "/dashboard/analytics" | "/dashboard/projects/[projectId]" | "/dashboard/vector-priority" | "/demos/theme-gallery" | "/errors" | "/gallery" | "/mcp" | "/mcp/status" | "/observation-lounge" | "/projects" | "/projects/[projectId]" | "/projects/new" | "/projects/preview" | "/quiz" | "/reports/architecture" | "/reports/observation-lounge" | "/settings" | "/test" | "/themes/a11y" | "/themes/template" | "/wizard" | "/workflows" | "/workflows/management"
type AppRouteHandlerRoutes = "/api/agent/engage" | "/api/agent/status" | "/api/auth/[...nextauth]" | "/api/auth/custom-signin" | "/api/codebase-changes" | "/api/content/delete" | "/api/content/retrieve" | "/api/content/store" | "/api/cost/optimization" | "/api/crew/observations" | "/api/crew/thoughts" | "/api/data/crew-contributions" | "/api/data/learning-categories" | "/api/data/learning-metrics" | "/api/data/progress/[taskId]" | "/api/data/recent-memories" | "/api/data/vectors" | "/api/events" | "/api/favicon" | "/api/health" | "/api/ingest/youtube" | "/api/ingest/youtube/batch" | "/api/knowledge/query" | "/api/lounge/avatars" | "/api/lounge/crew-advice" | "/api/lounge/crew-status" | "/api/lounge/latest" | "/api/mcp/[...endpoint]" | "/api/mcp/crew/roster" | "/api/mcp/errors" | "/api/mcp/errors/[id]/ignore" | "/api/mcp/errors/[id]/resolve" | "/api/mcp/settings" | "/api/mcp/settings/test" | "/api/mcp/status" | "/api/mcp/status/admin" | "/api/mcp/workflows/execute" | "/api/mcp/workflows/executions" | "/api/mcp/workflows/save" | "/api/mcp/workflows/storage" | "/api/memories/retrieve" | "/api/memories/stats" | "/api/progress/[taskId]" | "/api/revalidate" | "/api/security/assessment" | "/api/settings/create-table" | "/api/settings/diagnose" | "/api/settings/retrieve" | "/api/settings/store" | "/api/settings/test-supabase" | "/api/socket" | "/api/socket/io" | "/api/sync/pending" | "/api/sync/status" | "/api/sync/update" | "/api/theme/test" | "/api/themes/[theme]/tokens" | "/api/themes/dashboard/tokens" | "/api/themes/project/[project]" | "/api/themes/project/[project]/tokens" | "/api/ux/analytics" | "/api/workflows/[id]/mermaid"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]" | "/bridge/control/[[...path]]" | "/bridge/gallery/[[...path]]" | "/bridge/projects/alpha/[[...path]]" | "/bridge/projects/beta/[[...path]]" | "/bridge/projects/gamma/[[...path]]" | "/bridge/projects/temporal/[[...path]]" | "/bridge/quiz/[[...path]]" | "/bridge/wizard/[[...path]]" | "/observation-lounge"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/[[...path]]": { "path"?: string[]; }
  "/api/agent/engage": {}
  "/api/agent/status": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/custom-signin": {}
  "/api/codebase-changes": {}
  "/api/content/delete": {}
  "/api/content/retrieve": {}
  "/api/content/store": {}
  "/api/cost/optimization": {}
  "/api/crew/observations": {}
  "/api/crew/thoughts": {}
  "/api/data/crew-contributions": {}
  "/api/data/learning-categories": {}
  "/api/data/learning-metrics": {}
  "/api/data/progress/[taskId]": { "taskId": string; }
  "/api/data/recent-memories": {}
  "/api/data/vectors": {}
  "/api/events": {}
  "/api/favicon": {}
  "/api/health": {}
  "/api/ingest/youtube": {}
  "/api/ingest/youtube/batch": {}
  "/api/knowledge/query": {}
  "/api/lounge/avatars": {}
  "/api/lounge/crew-advice": {}
  "/api/lounge/crew-status": {}
  "/api/lounge/latest": {}
  "/api/mcp/[...endpoint]": { "endpoint": string[]; }
  "/api/mcp/crew/roster": {}
  "/api/mcp/errors": {}
  "/api/mcp/errors/[id]/ignore": { "id": string; }
  "/api/mcp/errors/[id]/resolve": { "id": string; }
  "/api/mcp/settings": {}
  "/api/mcp/settings/test": {}
  "/api/mcp/status": {}
  "/api/mcp/status/admin": {}
  "/api/mcp/workflows/execute": {}
  "/api/mcp/workflows/executions": {}
  "/api/mcp/workflows/save": {}
  "/api/mcp/workflows/storage": {}
  "/api/memories/retrieve": {}
  "/api/memories/stats": {}
  "/api/progress/[taskId]": { "taskId": string; }
  "/api/revalidate": {}
  "/api/security/assessment": {}
  "/api/settings/create-table": {}
  "/api/settings/diagnose": {}
  "/api/settings/retrieve": {}
  "/api/settings/store": {}
  "/api/settings/test-supabase": {}
  "/api/socket": {}
  "/api/socket/io": {}
  "/api/sync/pending": {}
  "/api/sync/status": {}
  "/api/sync/update": {}
  "/api/theme/test": {}
  "/api/themes/[theme]/tokens": { "theme": string; }
  "/api/themes/dashboard/tokens": {}
  "/api/themes/project/[project]": { "project": string; }
  "/api/themes/project/[project]/tokens": { "project": string; }
  "/api/ux/analytics": {}
  "/api/workflows/[id]/mermaid": { "id": string; }
  "/auth/signin": {}
  "/bridge/control/[[...path]]": { "path"?: string[]; }
  "/bridge/gallery/[[...path]]": { "path"?: string[]; }
  "/bridge/projects/alpha/[[...path]]": { "path"?: string[]; }
  "/bridge/projects/beta/[[...path]]": { "path"?: string[]; }
  "/bridge/projects/gamma/[[...path]]": { "path"?: string[]; }
  "/bridge/projects/temporal/[[...path]]": { "path"?: string[]; }
  "/bridge/quiz/[[...path]]": { "path"?: string[]; }
  "/bridge/wizard/[[...path]]": { "path"?: string[]; }
  "/clear-state": {}
  "/creative/[projectId]": { "projectId": string; }
  "/dashboard": {}
  "/dashboard/analytics": {}
  "/dashboard/projects/[projectId]": { "projectId": string; }
  "/dashboard/vector-priority": {}
  "/demos/theme-gallery": {}
  "/errors": {}
  "/gallery": {}
  "/mcp": {}
  "/mcp/status": {}
  "/observation-lounge": {}
  "/projects": {}
  "/projects/[projectId]": { "projectId": string; }
  "/projects/new": {}
  "/projects/preview": {}
  "/quiz": {}
  "/reports/architecture": {}
  "/reports/observation-lounge": {}
  "/settings": {}
  "/test": {}
  "/themes/a11y": {}
  "/themes/template": {}
  "/wizard": {}
  "/workflows": {}
  "/workflows/management": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
