#!/bin/bash
# Cursor AI State Recovery Script
# 
# Comprehensive state recovery that runs on Cursor AI startup
# Detects what's missing and recovers as much as possible

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$PROJECT_ROOT"

echo "🔄 Cursor AI State Recovery"
echo "=========================="
echo ""

# Check if we're in the right directory
if [ ! -f "package.json" ]; then
  echo "⚠️  Not in project root. Skipping state recovery."
  exit 0
fi

# Step 1: Recover state
echo "📋 Step 1: Recovering State..."
echo "-------------------------------"
if npm run cursor:state:recover > /dev/null 2>&1; then
  echo "✅ State recovery complete"
else
  echo "⚠️  State recovery had issues (this is okay if no state was saved)"
fi
echo ""

# Step 2: Restore layout
echo "📐 Step 2: Restoring Layout..."
echo "-------------------------------"
if npm run cursor:layout:restore > /dev/null 2>&1; then
  echo "✅ Layout restoration complete"
else
  echo "⚠️  Layout restoration had issues (this is okay if no layout was saved)"
fi
echo ""

# Step 3: Verify Alex AI state
echo "🧠 Step 3: Verifying Alex AI State..."
echo "--------------------------------------"

MEMORIES_FILE=".cursor/alex-ai/crew-memories.md"
PROMPT_FILE=".cursor/alex-ai/cursor-startup-prompt.md"

if [ -f "$MEMORIES_FILE" ]; then
  echo "✅ Alex AI memories found"
else
  echo "⚠️  Alex AI memories missing - will be loaded by startup task"
fi

if [ -f "$PROMPT_FILE" ]; then
  echo "✅ Alex AI prompt found"
else
  echo "⚠️  Alex AI prompt missing - will be generated by startup task"
fi
echo ""

# Step 4: Summary
echo "📊 Recovery Summary:"
echo "===================="
echo "✅ State recovery system active"
echo "✅ Layout restoration active"
echo "✅ Alex AI startup tasks will complete recovery"
echo ""
echo "💡 If anything is missing, it will be restored by:"
echo "   • Startup tasks (configured in .vscode/tasks.json)"
echo "   • Alex AI memory loading"
echo "   • Layout restoration"
echo ""

