#!/bin/bash

# 🖖 Local Development Server - DDD Controller Layer Integration
# 
# Complete local development setup that:
# 1. Cleans and restarts Next.js dashboard
# 2. Verifies connection to n8n controller layer
# 3. Verifies connection to MCP controller layer
# 4. Loads environment variables from ~/.zshrc
# 5. Starts dashboard with proper DDD architecture connections
#
# Crew: La Forge (Infrastructure), Uhura (Integration), Data (Verification)

set -e

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DASHBOARD_DIR="$ROOT_DIR/dashboard"
SCRIPTS_DIR="$ROOT_DIR/scripts"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}🖖 Local Development Server - DDD Controller Layer Integration${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Step 1: Load environment variables from ~/.zshrc
echo -e "${YELLOW}📋 Step 1: Loading environment variables...${NC}"
echo ""

if [ -f "$HOME/.zshrc" ]; then
  # Source zshrc to get environment variables
  source "$HOME/.zshrc" >/dev/null 2>&1 || true
  
  # Extract key variables
  export N8N_API_URL="${N8N_API_URL:-https://n8n.pbradygeorgen.com/api/v1}"
  export N8N_API_KEY="${N8N_API_KEY:-}"
  export MCP_API_URL="${MCP_API_URL:-https://mcp.pbradygeorgen.com}"
  export MCP_API_KEY="${MCP_API_KEY:-${N8N_API_KEY}}"
  export SUPABASE_URL="${SUPABASE_URL:-}"
  export SUPABASE_ANON_KEY="${SUPABASE_ANON_KEY:-}"
  export OPENROUTER_API_KEY="${OPENROUTER_API_KEY:-}"
  
  echo -e "   ${GREEN}✅${NC} Environment variables loaded from ~/.zshrc"
  echo -e "   ${BLUE}📍${NC} N8N API URL: ${N8N_API_URL}"
  echo -e "   ${BLUE}📍${NC} MCP API URL: ${MCP_API_URL}"
  echo ""
else
  echo -e "   ${YELLOW}⚠️${NC} ~/.zshrc not found, using defaults"
  echo ""
fi

# Step 2: Verify controller layer connections
echo -e "${YELLOW}🔍 Step 2: Verifying controller layer connections...${NC}"
echo ""

# Check n8n connection
echo -e "   ${BLUE}🔗${NC} Checking n8n controller layer..."
if [ -n "$N8N_API_KEY" ] && [ -n "$N8N_API_URL" ]; then
  N8N_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
    -H "X-N8N-API-KEY: $N8N_API_KEY" \
    "$N8N_API_URL/workflows" 2>/dev/null || echo "000")
  
  if [ "$N8N_STATUS" = "200" ]; then
    echo -e "   ${GREEN}✅${NC} n8n controller layer: Connected"
  else
    echo -e "   ${YELLOW}⚠️${NC} n8n controller layer: Not accessible (HTTP $N8N_STATUS)"
    echo -e "      ${YELLOW}💡${NC} Dashboard will work in development mode without n8n"
  fi
else
  echo -e "   ${YELLOW}⚠️${NC} n8n credentials not configured"
  echo -e "      ${YELLOW}💡${NC} Dashboard will work in development mode without n8n"
fi
echo ""

# Check MCP connection
echo -e "   ${BLUE}🔗${NC} Checking MCP controller layer..."
if [ -n "$MCP_API_KEY" ] && [ -n "$MCP_API_URL" ]; then
  MCP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
    -H "X-API-Key: $MCP_API_KEY" \
    "$MCP_API_URL/healthz" 2>/dev/null || echo "000")
  
  if [ "$MCP_STATUS" = "200" ]; then
    echo -e "   ${GREEN}✅${NC} MCP controller layer: Connected"
  else
    echo -e "   ${YELLOW}⚠️${NC} MCP controller layer: Not accessible (HTTP $MCP_STATUS)"
    echo -e "      ${YELLOW}💡${NC} Dashboard will work in development mode without MCP"
  fi
else
  echo -e "   ${YELLOW}⚠️${NC} MCP credentials not configured"
  echo -e "      ${YELLOW}💡${NC} Dashboard will work in development mode without MCP"
fi
echo ""

# Step 3: Clean restart dashboard (using clean-restart script)
echo -e "${YELLOW}🧹 Step 3: Cleaning and restarting dashboard...${NC}"
echo ""

# Use the clean-restart script if it exists, otherwise do it manually
CLEAN_RESTART_SCRIPT="$SCRIPTS_DIR/dashboard/clean-restart.sh"
if [ -f "$CLEAN_RESTART_SCRIPT" ]; then
  echo -e "   ${BLUE}📜${NC} Using clean-restart script..."
  cd "$DASHBOARD_DIR" || exit 1
  # Extract just the cleanup part (kill processes and clear caches)
  lsof -ti:3000 | xargs kill -9 2>/dev/null || true
  lsof -ti:3001 | xargs kill -9 2>/dev/null || true
  sleep 1
  rm -rf .next node_modules/.cache .turbo .swc .next.lock 2>/dev/null || true
  echo -e "   ${GREEN}✅${NC} Clean restart complete"
else
  # Manual cleanup
  cd "$DASHBOARD_DIR" || exit 1
  echo -e "   ${BLUE}🛑${NC} Stopping existing processes..."
  lsof -ti:3000 | xargs kill -9 2>/dev/null || true
  lsof -ti:3001 | xargs kill -9 2>/dev/null || true
  sleep 1
  echo -e "   ${GREEN}✅${NC} Processes stopped"
  echo ""
  echo -e "   ${BLUE}🧹${NC} Clearing dev caches..."
  rm -rf .next node_modules/.cache .turbo .swc .next.lock 2>/dev/null || true
  echo -e "   ${GREEN}✅${NC} Caches cleared"
fi
echo ""

# Step 4: Create/update .env.local with controller layer URLs
echo -e "${YELLOW}⚙️  Step 4: Configuring environment...${NC}"
echo ""

ENV_FILE="$DASHBOARD_DIR/.env.local"

cat > "$ENV_FILE" <<EOF
# DDD Controller Layer Configuration
# Generated by local-dev-start.sh

# Next.js Configuration
NODE_ENV=development
PORT=3000

# n8n Controller Layer (Primary)
NEXT_PUBLIC_N8N_API_URL=${N8N_API_URL}
NEXT_PUBLIC_N8N_API_KEY=${N8N_API_KEY}

# MCP Controller Layer (Primary)
NEXT_PUBLIC_MCP_API_URL=${MCP_API_URL}
NEXT_PUBLIC_MCP_API_KEY=${MCP_API_KEY}

# Supabase Data Layer
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}

# OpenRouter (for crew coordination)
NEXT_PUBLIC_OPENROUTER_API_KEY=${OPENROUTER_API_KEY}

# Development Mode
NEXT_PUBLIC_DEV_MODE=true
EOF

echo -e "   ${GREEN}✅${NC} Environment file created: .env.local"
echo ""

# Step 5: Verify dependencies
echo -e "${YELLOW}📦 Step 5: Verifying dependencies...${NC}"
echo ""

if [ ! -d "node_modules" ]; then
  echo -e "   ${YELLOW}⚠️${NC} node_modules not found, installing..."
  npm install
  echo -e "   ${GREEN}✅${NC} Dependencies installed"
else
  echo -e "   ${GREEN}✅${NC} Dependencies exist"
fi
echo ""

# Step 6: Start dev server
echo -e "${YELLOW}🚀 Step 6: Starting Next.js dev server...${NC}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${GREEN}✅ Local Development Server Ready!${NC}"
echo ""
echo -e "   ${BLUE}🌐${NC} Dashboard URL: ${GREEN}http://localhost:3000${NC}"
echo ""
echo -e "   ${BLUE}🔗${NC} Controller Layer Connections:"
echo -e "      ${BLUE}•${NC} n8n: ${N8N_API_URL}"
echo -e "      ${BLUE}•${NC} MCP: ${MCP_API_URL}"
echo ""
echo -e "   ${BLUE}📋${NC} DDD Architecture:"
echo -e "      ${BLUE}•${NC} Client Layer: Next.js Dashboard (localhost:3000)"
echo -e "      ${BLUE}•${NC} Controller Layer: n8n + MCP (remote)"
echo -e "      ${BLUE}•${NC} Data Layer: Supabase (remote)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Step 7: Open browser tabs after server starts
echo -e "${YELLOW}🌐 Step 7: Opening browser tabs for live update testing...${NC}"
echo ""

# Function to open browser tabs after a delay
open_browser_tabs() {
  sleep 8  # Wait for server to start
  
  echo -e "   ${BLUE}📱${NC} Opening browser tabs..."
  
  # Open main dashboard
  if command -v open >/dev/null 2>&1; then
    # macOS
    open "http://localhost:3000" 2>/dev/null || true
    echo -e "   ${GREEN}✅${NC} Opened http://localhost:3000"
    
    # Open test page if it exists
    sleep 1
    open "http://localhost:3000/test" 2>/dev/null || true
    echo -e "   ${GREEN}✅${NC} Opened http://localhost:3000/test"
  elif command -v xdg-open >/dev/null 2>&1; then
    # Linux
    xdg-open "http://localhost:3000" 2>/dev/null || true
    echo -e "   ${GREEN}✅${NC} Opened http://localhost:3000"
    sleep 1
    xdg-open "http://localhost:3000/test" 2>/dev/null || true
    echo -e "   ${GREEN}✅${NC} Opened http://localhost:3000/test"
  elif command -v start >/dev/null 2>&1; then
    # Windows
    start "http://localhost:3000" 2>/dev/null || true
    echo -e "   ${GREEN}✅${NC} Opened http://localhost:3000"
    sleep 1
    start "http://localhost:3000/test" 2>/dev/null || true
    echo -e "   ${GREEN}✅${NC} Opened http://localhost:3000/test"
  else
    echo -e "   ${YELLOW}⚠️${NC} Could not auto-open browser. Please open manually:"
    echo -e "      ${BLUE}•${NC} http://localhost:3000"
    echo -e "      ${BLUE}•${NC} http://localhost:3000/test"
  fi
  
  echo ""
  echo -e "   ${BLUE}🧪${NC} Live Update Testing:"
  echo -e "      ${BLUE}•${NC} Make changes to dashboard components"
  echo -e "      ${BLUE}•${NC} Watch for real-time updates across tabs"
  echo -e "      ${BLUE}•${NC} Test controller layer integration (n8n/MCP)"
  echo ""
}

# Start browser tabs in background
open_browser_tabs &

# Start the dev server
npm run dev

